- name: "type:bug"
  color: "d73a4a"
  description: "Something isn't working in scripts, docs, or remaster flow"
- name: "type:feature"
  color: "a2eeef"
  description: "New capability or enhancement"
- name: "type:docs"
  color: "c5def5"
  description: "Documentation-only change"
- name: "type:build"
  color: "bfdadc"
  description: "ISO remastering, packaging, or bootstrap tooling"
- name: "status:triage"
  color: "f9d0c4"
  description: "Awaiting review or categorization"
- name: "priority:high"
  color: "b60205"
  description: "Blocks a milestone or release"
- name: "priority:normal"
  color: "0e8a16"
  description: "Normal priority tracked item"
- name: "priority:low"
  color: "fef2c0"
  description: "Nice-to-have or low urgency"
- name: "phase:1-setup"
  color: "1d76db"
  description: "Roadmap Phase 1: Project Setup"
- name: "phase:2-iso-skeleton"
  color: "0052cc"
  description: "Roadmap Phase 2: ISO Remaster Skeleton"
- name: "phase:3-bootstrap"
  color: "5319e7"
  description: "Roadmap Phase 3: Developer Bootstrap"
